# -*- coding: utf-8 -*-
"""Yolo 11 Full Plant Disease Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17nbZWjIQW4Tb6TfOs4ImOqKR4L3LLVq1
"""

!pip install split-folders
!pip install ultralytics

!mkdir -p ~/.kaggle
!echo '{"username":"sreenandrajeev","key":"e226ee440bb50ab15a0f1b99b3b8530c"}' > ~/.kaggle/kaggle.json
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d vipoooool/new-plant-diseases-dataset

!unzip new-plant-diseases-dataset.zip

!mkdir -p /content/Train
!cp -r "/content/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train/" /content/Train

import splitfolders
from ultralytics import YOLO
from IPython.display import Image as IPImage
from PIL import Image
import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc, precision_recall_fscore_support, accuracy_score
from tqdm import tqdm
import torch

!mkdir -p /content/Dataset

input_dir='/content/Train/train'
output_dir='/content/Dataset'

splitfolders.ratio(input_dir, output=output_dir, seed=8086 , ratio=(0.8,0.2), group_prefix=None)

model=YOLO('yolo11n-cls.pt')
results=model.train(data='/content/Dataset', epochs=20, imgsz=256)

IPImage('/content/runs/classify/train5/results.png',width=500)

model=YOLO('/content/runs/classify/train5/weights/best.pt')
results=model('/content/Dataset/train/Potato___healthy/00fc2ee5-729f-4757-8aeb-65c3355874f2___RS_HL 1864.JPG')
results[0].show()

train_data_path = '/content/Dataset/train'
class_names = []

for i in os.listdir(train_data_path):
    class_names.append(i)

class_names.sort()
class_names.pop()
for i in class_names:
    print(i)

model = YOLO('/content/runs/classify/train5/weights/best.pt')

val_data_path = '/content/Dataset/val'


class_to_index = {class_name: index for index, class_name in enumerate(class_names)}

def get_predictions_and_labels(model, val_data_path, class_to_index):
    predicted_classes = []
    true_labels = []

    for class_name in os.listdir(val_data_path):
        class_path = os.path.join(val_data_path, class_name)
        for image_name in os.listdir(class_path):
            image_path = os.path.join(class_path, image_name)
            results = model(image_path)


            true_labels.append(class_to_index[class_name])


            predicted_classes.append(results[0].probs.top1)

    return predicted_classes, true_labels

predicted_classes, true_labels = get_predictions_and_labels(model, val_data_path, class_to_index)


precision, recall, f1_score, _ = precision_recall_fscore_support(true_labels, predicted_classes, average=None)
accuracy = accuracy_score(true_labels, predicted_classes)

for i, class_name in enumerate(class_names):
    print(f"Class: {class_name}")
    print(f"  Precision: {precision[i]:.4f}")
    print(f"  Recall: {recall[i]:.4f}")
    print(f"  F1-score: {f1_score[i]:.4f}")

true_labels_binarized = label_binarize(true_labels, classes=list(range(len(class_names))))

predicted_probabilities = []
for class_name in os.listdir(val_data_path):
    class_path = os.path.join(val_data_path, class_name)
    for image_name in os.listdir(class_path):
        image_path = os.path.join(class_path, image_name)
        results = model(image_path)
        predicted_probabilities.append(results[0].probs.data.cpu().numpy())


fpr = dict()
tpr = dict()
roc_auc = dict()
for i in range(len(class_names)):
    fpr[i], tpr[i], _ = roc_curve(true_labels_binarized[:, i], [prob[i] for prob in predicted_probabilities])
    roc_auc[i] = auc(fpr[i], tpr[i])


plt.figure()
for i, class_name in enumerate(class_names):
    plt.plot(fpr[i], tpr[i], label=f'{class_name} (AUC = {roc_auc[i]:.2f})')

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.show()

plt.figure(figsize=(10, 8))  # Increase figure size for better visibility
colors = cm.rainbow(np.linspace(0, 1, len(class_names)))  # Use a colormap for distinct curves

for i, class_name in enumerate(class_names):
    plt.plot(fpr[i], tpr[i], color=colors[i], lw=2,
             label=f'{class_name} (AUC = {roc_auc[i]:.2f})')

plt.plot([0, 1], [0, 1], color='gray', linestyle='--')  # Add a diagonal line for reference
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate', fontsize=12)  # Increase font size for labels
plt.ylabel('True Positive Rate', fontsize=12)
plt.title('Receiver Operating Characteristic (ROC) Curve', fontsize=14)  # Increase title font size
plt.legend(loc="lower right", fontsize=8)  # Adjust legend font size and location
plt.grid(True, alpha=0.3)  # Add a grid for better readability
plt.tight_layout()  # Adjust layout to prevent overlapping elements
plt.show()

IPImage("/content/runs/classify/train5/results.png")

IPImage("/content/runs/classify/train5/confusion_matrix.png")